services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: innovadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  back-despachos:
    build: ./back-Despachos_SpringBoot
    container_name: back-despachos
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovadb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8080"

  back-ventas:
    build: ./back-Ventas_SpringBoot
    container_name: back-ventas
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovadb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8082:8080"

  frontend:
    build: ./front_despacho
    container_name: frontend
    depends_on:
      - back-despachos
      - back-ventas
    ports:
      - "80:80"

volumes:
  db_data:
